{% set version = "3.6.2" %}

package:
  name: types-orjson
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-orjson/types-orjson-{{ version }}.tar.gz
  sha256: cf9afcc79a86325c7aff251790338109ed6f6b1bab09d2d4262dd18c85a3c638

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/orjson-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for orjson
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
